### ISSUE TITLE
Weird to connect to mongo  server localhost:27017

### ISSUE THREAD

**Issue by niaomingjian** [authoronloadcode/Quarts-Scheduling-using-Rest-API-with-Spring-Boot-and-MongoDB#1]
````
org.quartz.jobStore.mongoUri=mongodb://testdb1:testdb1@192.168.106.241:31717/testdb?authSource=testdb
org.quartz.jobStore.dbName=testdb
````
From the log, looks like the program still also wants to connect to mongo  server localhost:27017 with the config above, then failed. So weird.

````
> Task :bootRun
{spring.web.resources.chain.cache=false, spring.web.resources.cache.period=0}

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.0)

2021-08-10 17:36:46.405  INFO 18040 --- [  restartedMain] c.onloadcode.quartz.lesson.Application   : Starting Application using Java 11.0.12 on DESKTOP-DQORARP with PID 18040 (E:\WS\Quarts-Scheduling-using-Rest-API-with-Spring-Boot-and-MongoDB-main\build\classes\java\main started by Young in E:\WS\Quarts-Scheduling-using-Rest-API-with-Spring-Boot-and-MongoDB-main)
2021-08-10 17:36:46.407  INFO 18040 --- [  restartedMain] c.onloadcode.quartz.lesson.Application   : No active profile set, falling back to default profiles: default
2021-08-10 17:36:46.444  INFO 18040 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-08-10 17:36:46.444  INFO 18040 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-08-10 17:36:46.956  INFO 18040 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2021-08-10 17:36:46.968  INFO 18040 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8 ms. Found 0 MongoDB repository interfaces.
2021-08-10 17:36:47.762  INFO 18040 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-08-10 17:36:47.771  INFO 18040 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-08-10 17:36:47.771  INFO 18040 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.39]
2021-08-10 17:36:47.857  INFO 18040 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-08-10 17:36:47.857  INFO 18040 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1412 ms
2021-08-10 17:36:47.920  INFO 18040 --- [  restartedMain] c.o.q.lesson.config.JobConfiguration     : onloadcode Quartz Scheduler initialized
2021-08-10 17:36:47.946  INFO 18040 --- [  restartedMain] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
2021-08-10 17:36:47.953  INFO 18040 --- [  restartedMain] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2021-08-10 17:36:47.954  INFO 18040 --- [  restartedMain] org.quartz.core.QuartzScheduler          : Quartz Scheduler v.2.3.2 created.
2021-08-10 17:36:48.000  INFO 18040 --- [  restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.106.241:31717], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
2021-08-10 17:36:48.034  INFO 18040 --- [  restartedMain] org.mongodb.driver.cluster               : Cluster description not yet available. Waiting for 30000 ms before timing out
2021-08-10 17:36:48.042  INFO 18040 --- [8.106.241:31717] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:1230}] to 192.168.106.241:31717
2021-08-10 17:36:48.042  INFO 18040 --- [8.106.241:31717] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:1231}] to 192.168.106.241:31717
2021-08-10 17:36:48.043  INFO 18040 --- [8.106.241:31717] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=192.168.106.241:31717, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=12457200}
2021-08-10 17:36:48.382  INFO 18040 --- [  restartedMain] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:3, serverValue:1232}] to 192.168.106.241:31717
2021-08-10 17:36:49.546  INFO 18040 --- [  restartedMain] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'onloadcode-job-scheduler' with instanceId 'onloadcode'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'com.novemberain.quartz.mongodb.MongoDBJobStore' - which supports persistence. and is not clustered.

2021-08-10 17:36:49.547  INFO 18040 --- [  restartedMain] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'onloadcode-job-scheduler' initialized from an externally provided properties instance.
2021-08-10 17:36:49.547  INFO 18040 --- [  restartedMain] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
2021-08-10 17:36:49.547  INFO 18040 --- [  restartedMain] org.quartz.core.QuartzScheduler          : JobFactory set to: com.onloadcode.quartz.lesson.config.AutowiringSpringBeanJobFactory@686364e
2021-08-10 17:36:49.703  INFO 18040 --- [  restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-08-10 17:36:50.030  INFO 18040 --- [  restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
2021-08-10 17:36:50.179  INFO 18040 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2021-08-10 17:36:50.207  INFO 18040 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-08-10 17:36:50.209  INFO 18040 --- [  restartedMain] o.s.s.quartz.SchedulerFactoryBean        : Starting Quartz Scheduler now
2021-08-10 17:36:50.209  INFO 18040 --- [  restartedMain] org.quartz.core.QuartzScheduler          : Scheduler onloadcode-job-scheduler_$_onloadcode started.
2021-08-10 17:36:50.218  INFO 18040 --- [  restartedMain] c.onloadcode.quartz.lesson.Application   : Started Application in 4.125 seconds (JVM running for 4.564)
2021-08-10 17:36:50.225  INFO 18040 --- [  restartedMain] c.onloadcode.quartz.lesson.Application   :   ___                       _          ____         _                _         _  _                             _                 ____              _        _     ____   ___             _  _    _       ____                _                 ____                 _                       _   __  __                              ____   ____   
 / _ \  _   _   __ _  _ __ | |_  ___  / ___|   ___ | |__    ___   __| | _   _ | |(_) _ __    __ _   _   _  ___ (_) _ __    __ _  |  _ \   ___  ___ | |_     / \   |  _ \ |_ _| __      __(_)| |_ | |__   / ___|  _ __   _ __ (_) _ __    __ _  | __ )   ___    ___  | |_    __ _  _ __    __| | |  \/  |  ___   _ __    __ _   ___  |  _ \ | __ )  
| | | || | | | / _` || '__|| __|/ __| \___ \  / __|| '_ \  / _ \ / _` || | | || || || '_ \  / _` | | | | |/ __|| || '_ \  / _` | | |_) | / _ \/ __|| __|   / _ \  | |_) | | |  \ \ /\ / /| || __|| '_ \  \___ \ | '_ \ | '__|| || '_ \  / _` | |  _ \  / _ \  / _ \ | __|  / _` || '_ \  / _` | | |\/| | / _ \ | '_ \  / _` | / _ \ | | | ||  _ \  
| |_| || |_| || (_| || |   | |_ \__ \  ___) || (__ | | | ||  __/| (_| || |_| || || || | | || (_| | | |_| |\__ \| || | | || (_| | |  _ < |  __/\__ \| |_   / ___ \ |  __/  | |   \ V  V / | || |_ | | | |  ___) || |_) || |   | || | | || (_| | | |_) || (_) || (_) || |_  | (_| || | | || (_| | | |  | || (_) || | | || (_| || (_) || |_| || |_) | 
 \__\_\ \__,_| \__,_||_|    \__||___/ |____/  \___||_| |_| \___| \__,_| \__,_||_||_||_| |_| \__, |  \__,_||___/|_||_| |_| \__, | |_| \_\ \___||___/ \__| /_/   \_\|_|    |___|   \_/\_/  |_| \__||_| |_| |____/ | .__/ |_|   |_||_| |_| \__, | |____/  \___/  \___/  \__|  \__,_||_| |_| \__,_| |_|  |_| \___/ |_| |_| \__, | \___/ |____/ |____/  
                                                                                            |___/                         |___/                                                                                 |_|                     |___/                                                                          |___/                       

2021-08-10 17:36:52.053  INFO 18040 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70) ~[mongodb-driver-core-4.1.1.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:143) ~[mongodb-driver-core-4.1.1.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:188) ~[mongodb-driver-core-4.1.1.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144) ~[mongodb-driver-core-4.1.1.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method) ~[na:na]
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:608) ~[na:na]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:78) ~[mongodb-driver-core-4.1.1.jar:na]
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79) ~[mongodb-driver-core-4.1.1.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[mongodb-driver-core-4.1.1.jar:na]
	... 4 common frames omitted

Caused by: java.net.ConnectException: Connection refused: connect
````

**Comment by niaomingjian** [comment]
With the following config
````
org.quartz.jobStore.mongoUri=mongodb://testdb1:testdb1@192.168.106.241:31717/testdb?authSource=admin
org.quartz.jobStore.dbName=testdb
````

Task :bootRun FAILED

````
Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server 192.168.106.241:31717. The full response is {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed"}
````

I could use client tool (Robo 3T) to connect to the server with testdb1:testdb1
